.TH IMAZESRV 6 "10 December 2001"
.SH NAME
imazesrv \- the server for iMaze
.SH SYNOPSIS
.in +\w'\fBimazesrv \fR'u
.ti -\w'\fBimazesrv \fR'u
.B imazesrv
[\ \fB\-hACFIQR\fR\ ]
[\ \fB\-c\fI\ cycle-time\fR\ ]
[\ \fB\-l\fR\ {\fIlog-file\fR|-}\ ]
[\ \fB\-p\fI\ port\fR\ ]
.I lab-file
.SH DESCRIPTION
.LP
.B imazesrv
is a TCP/IP server for the multi-player network action game
.BR imaze (6).
.SH OPTIONS
.TP
.B \-h
Print command line option help.
.TP
.BI \-c " cycle-time"
Use a
.I cycle-time
ms step for the game clock.
Allowed is 15-150ms.
The default value is 60ms.
Use lower values for faster game and higher values for slower games, 
e.g. bad network connections.
.TP
.BI \-l " log-file"
Enable logging of connections to
.IR log-file .
.TP
.B \-l -
Enable logging of connections to standard output.
.TP
.BI \-p " port"
Use
.I port
instead of the default TCP port.
.TP
.B \-A
Enable auto-answer shot for all players.
.TP
.B \-C
Make all players colorless.
.TP
.B \-F
Make all players faceless.
.TP
.B \-I
Make all players invisible.
.TP
.B \-Q
Allow quickturn for all players.
.TP
.B \-R
Enable reflective shot for all players.
.SH SEE ALSO
.BR genlab (6),
.BR imaze (6),
.BR imazestat (6),
.BR ninja (6),
.BR xlabed (6)
