.TH IMAZESTAT 6 "10 December 2001"
.SH NAME
imazestat \- print current players on iMaze server
.SH SYNOPSIS
.in +\w'\fBimazestat \fR'u
.ti -\w'\fBimazestat \fR'u
.B imazestat
[\ \fB\-h\fR\ ]
\fIserver-host\fR[\fB:\fIserver-port\fR]
.SH DESCRIPTION
.LP
.B imazestat
prints the current players, their color, kill-message,
and client version on a server for the multi-player network action game
.BR imaze (6).
.SH OPTIONS
.TP
.B \-h
Print command line option help.
.SH SEE ALSO
.BR genlab (6),
.BR imaze (6),
.BR imazesrv (6),
.BR ninja (6),
.BR xlabed (6)
