.TH NINJA 6 "10 December 2001"
.SH NAME
ninja \- a simple automated iMaze client
.SH SYNOPSIS
.in +\w'\fBninja \fR'u
.ti -\w'\fBninja \fR'u
.B ninja
[\ \fB\-hiQ\fR\ ]
[\ \fB\-H \fIserver-host\fR[\fB:\fIserver-port\fR]\ ]
[\ \fB\-m\fR\ \fImessage\fR\ ]
[\ \fB\-s \fIshot-percentage\fR\ ]
[\ \fB\-t \fIcolor-index\fR\ ]
.SH DESCRIPTION
.LP
.B ninja
is an automated non-interactive TCP/IP client for the
multi-player network action game iMaze.
.SH OPTIONS
.TP
.B \-h
Print command line option help.
.TP
\fB\-H \fIserver-host\fR[\fB:\fIserver-port\fR]
The host and port
.IR imazesrv (6)
is using.
.TP
.B \-i
Use an inverse strategy: ninja runs away from the nearest
player (backwards).
.TP
.BI -m\  message
Message that is sent to other players when they are killed.
.TP
.B \-Q
Use quickturn if available.
.TP
.BI -s\  shot-percentage
Probability that
.I ninja
will shoot when no shot of his is there. Default is 100.
.TP
.BI -t\  color-index
Run towards player with color
.I color-index
as reported by
.IR imazestat (6).
.SH SEE ALSO
.BR genlab (6),
.BR imaze (6),
.BR imazesrv (6),
.BR imazestat (6),
.BR xlabed (6)
.SH BUGS
.LP
The
.I ninja
is really dumb.
